 # MINI PROJECT ACTIVITY
## PROJECT TITLE : IRIS DATASET [Phase-5]

# Classification

In [2]:
import numpy as np
import pandas as pd
import warnings
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
from sklearn import metrics
from sklearn.datasets import load_iris  # Import the Iris dataset
warnings.filterwarnings(action='ignore')  # Turn off the warnings.

In [24]:
# Load the Iris dataset
iris = load_iris()

In [25]:
X = iris.data
y = iris.target

In [5]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Classification Tree

In [6]:
# Classification Tree
DTC = DecisionTreeClassifier(max_depth=10)
DTC.fit(X_train, y_train)
y_pred = DTC.predict(X_test)

# Calculate and print the accuracy of the classifier
accuracy = metrics.accuracy_score(y_test, y_pred)
print("Tree accuracy:", np.round(accuracy, 3))

Tree accuracy: 1.0


# Classification with KNN

In [7]:
# Classification with KNN
KNN = KNeighborsClassifier(n_neighbors=5)
KNN.fit(X_train, y_train)
y_pred = KNN.predict(X_test)

# Calculate and print the accuracy of the classifier
accuracy = metrics.accuracy_score(y_test, y_pred)
print("KNN accuracy:", np.round(accuracy, 3))

KNN accuracy: 1.0


# Classification with Logistic Regression

In [8]:
# Classification with Logistic Regression
LR = LogisticRegression()
LR.fit(X_train, y_train)
y_pred = LR.predict(X_test)

# Calculate and print the accuracy of the classifier
accuracy = metrics.accuracy_score(y_test, y_pred)
print("Logistic Regression accuracy:", np.round(accuracy, 3))

Logistic Regression accuracy: 1.0


# Predicting with a voting ensemble:¶

In [9]:
# Voting Classifier
VC = VotingClassifier(estimators=[('Tree', DTC), ('knn', KNN), ('Logistic', LR)], voting='hard')
VC.fit(X_train, y_train)
y_pred = VC.predict(X_test)

# Calculate and print the accuracy of the Voting Classifier
accuracy = metrics.accuracy_score(y_test, y_pred)
print("Voting Classifier Accuracy:", np.round(accuracy, 3))

Voting Classifier Accuracy: 1.0


In [10]:
# Voting Classifier
VC = VotingClassifier(estimators=[('Tree', DTC), ('knn', KNN), ('Logistic', LR)], voting='hard')
VC.fit(X_train, y_train)
y_pred = VC.predict(X_test)

# Calculate and print the accuracy of the Voting Classifier
accuracy = metrics.accuracy_score(y_test, y_pred)
print("Voting Classifier Accuracy:", np.round(accuracy, 3))

Voting Classifier Accuracy: 1.0


# Multi-class Classification

## Evaluation Metrics for Classification

In [18]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [19]:
# Encode target labels if needed
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [20]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)


In [21]:
# Print the evaluation metrics
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 1.0000


In [22]:
print("\nConfusion Matrix:")
print(conf_matrix)


Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [23]:
print("\nClassification Report:")
print(classification_rep)


Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



### Built and evaluated 6 regression models 🌸🤖 (Linear, Lasso, SVR, Decision Tree, Random Forest, Logistic) on the Iris dataset. Explored diverse algorithms to capture relationships. 📊Chose the best-performing model based on metrics like MSE or R-squared. For classification, leveraged common algorithms (Decision Trees, Random Forests, SVMs, k-NN) on Iris, focusing on metrics such as accuracy, precision, recall, and F1-score. 🌐🔍 Evaluated and selected the most suitable model for the classification task. 🏆